<nav>
    <div>
        <div>
            <a>AdLister</a>
        </div>
        <ul>
            <li><a>Login</a></li>
        </ul>
        <ul>
            <li><a>user</a></li>
        </ul>
    </div>
</nav>
